RobotName: "ModularBot"

GazeboXBotPlugin:
  control_rate: 0.00025
  gains:
    J0: {p: 0, d: 0}
    J1_A: {p: 0, d: 0}
    J2_A: {p: 0, d: 0}
    J3_A: {p: 0, d: 0}
    J4_A: {p: 0, d: 0}
    J5_A: {p: 0, d: 0}
    J6_A: {p: 0, d: 0}
    J1_B: {p: 0, d: 0}
    J2_B: {p: 0, d: 0}
    J3_B: {p: 0, d: 0}
    J4_B: {p: 0, d: 0}
    J5_B: {p: 0, d: 0}
    J6_B: {p: 0, d: 0}




HALInterface:
  lib_file: "libXBotEcat"
  lib_name: "ETHERCAT"

SCPLog:
  remote_username: "ModularBot"
  remote_ip_address: "10.24.4.77"
  remote_log_folder_path: "/home/ModularBot/MODULARBOT_LOG"

x_bot_ecat:
  name: XBotCore
  sdo_xddp_prefix :
  # periodic - priority if needed here


#
ec_board_ctrl:
  eth_iface: rteth0
  #eth_iface: eth1
  #sync_cycle_time_ns: 500000
  sync_cycle_time_ns: 1000000
  #sync_cycle_time_ns: 2000000
  #sync_cycle_time_ns: 5000000
  #sync_cycle_time_ns: 10000000
  #sync_cycle_time_ns: 0
  sync_cycle_offset_ns: 1000000000
  power_off_boards: false
  #use_pipes: false

firmware_update:
  #
  fw_path: ../examples/fw_update/fw_test/
  #slave_pos_list: [7]
  #slave_rId_list: [7]
  # all esc
  #slave_pos_list: [0]
  # all BigMotor
  #slave_pos_list: [-1]
  # all MedMotor
  #slave_pos_list: [-2]
  # all LowPower motor
  #slave_pos_list: [-3]
  # all CentAC motor
  slave_pos_list: [-4]
  #slave_pos_list: [1]

  cent_AC:
    m3:
      bin_file: cent_AC_m3.bin
      passwd: 0xA550
    c28:
      bin_file: cent_AC_c28.bin
      passwd: 0xDAD0

#############################
# GENERIC ESC config
#############################
