os: linux
language: cpp
compiler: g++
dist: bionic

branches:
  only:
    - binarization
    - /^v\d+\.\d+\.\d+.*$/  # version tags
  
notifications:
  email:
    recipients:
      - arturo.laurenzi@iit.it
    on_success: never
    on_failure: always

before_install:
  - rm -rf /opt/pyenv  # damn pyenv

before_script:
  - echo "Travis tag is $TRAVIS_TAG"
  - sudo apt update && sudo apt install python2.7 python-pip 
  - sudo pip install pyinstaller==3.6

script: 
  - pip install -e .
  - cd src/modular/web/
  - pyinstaller --onefile RobotBuilder.spec
  - ls dist/RobotBuilder  # fail if does not exist

deploy:
  provider: releases
  api_key: $GH_TOKEN
  file: dist/RobotBuilder
  skip_cleanup: true
  on:
    tags: true


