os: linux
dist: focal
language: python
cache: pip

branches:
  only:
    - python3
    - /^v\d+\.\d+\.\d+.*$/ # version tags

notifications:
  email:
    recipients:
      - edoardo.romiti@iit.it
      - arturo.laurenzi@iit.it
    on_success: never
    on_failure: always

install:
  - echo "Travis tag is $TRAVIS_TAG"
  - sudo apt update
  - sudo apt install lsb-release
  - sudo sh -c 'echo "deb http://packages.ros.org/ros/ubuntu $(lsb_release -sc) main" > /etc/apt/sources.list.d/ros-latest.list'
  - sudo apt install curl
  - curl -s https://raw.githubusercontent.com/ros/rosdistro/master/ros.asc | sudo apt-key add -
  - sudo apt update
  - sudo apt install ros-noetic-desktop-full 
  - pip install pyinstaller
  - pip install -e .

script:
  - source /opt/ros/noetic/setup.bash
  - cd src/modular/web/
  - pyinstaller RobotBuilder.spec
  - ls dist/RobotBuilder # fail if does not exist

deploy:
  provider: releases
  api_key: $GH_TOKEN
  file: dist/RobotBuilder
  skip_cleanup: true
  on:
    tags: true
