stack:
    -   - EE
EE:
    type: Interaction
    base_link: L_0a
    distal_link: L_1_A
    stiffness:
        - 50.0
        - 50.0
        - 50.0
        - 1.0
        - 1.0
        - 1.0
    damping:
        - 5.0
        - 5.0
        - 5.0
        - 0.0
        - 0.0
        - 0.0
