module_name: hexadecimal
module_aux: hexadecimal
m_1: float
I_xx_1: float
I_yy_1: float
I_zz_1: float
I_xy_1: float
I_yz_1: float
I_xz_1: float
rx_c_1: float
ry_c_1: float
rz_c_1: float
rx_1: float
ry_1: float
rz_1: float
q_w_1: float
q_x_1: float
q_y_1: float
q_z_1: float
m_2: float
I_xx_2: float
I_yy_2: float
I_zz_2: float
I_xy_2: float
I_yz_2: float
I_xz_2: float
rx_c_2: float
ry_c_2: float
rz_c_2: float
rx_2: float
ry_2: float
rz_2: float
q_w_2: float
q_x_2: float
q_y_2: float
q_z_2: float
gazebo: ''
