data_path: 'modular_data'
resources_path: 'modular_resources'
external_resources:
# the path to external resources must be absolute, even if by using variables (~, etc.)
  concert_resources_path: '$(ros2 pkg prefix --share concert_resources)'
  dagana_path: '$(ros2 pkg prefix --share dagana_urdf)'
  # whatever_resources_path: None
modularbot_path: 'modular_data/ModularBot'
deploy_dir: '~/robots'
