<?xml version="1.0"?>
<robot name="ModularBot" xmlns:xacro="http://ros.org/wiki/xacro">

    <xacro:property name="size1" value="0.05" />
    <xacro:property name="size2" value="0.055" />
    <xacro:property name="size3" value="0.06" />
    <!-- <xacro:property name="leglen" value="0.3" /> -->
    <xacro:property name="len1" value="0.4" />
    <xacro:property name="len2" value="0.6" />
    <xacro:property name="len3" value="0.8" />
    <xacro:property name="mass" value="1" />
    <!-- <xacro:property name="pi" value="3.1415" /> -->

    <material name="blue">
        <color rgba="0 0 0.8 1"/>
    </material>

    <material name="black">
        <color rgba="0 0 0 1"/>
    </material>

    <material name="white">
        <color rgba="1 1 1 1"/>
    </material>

    <material name="grey">
        <color rgba="0.5 0.5 0.5 1"/>
    </material>

    <xacro:macro name="default_inertial" params="mass">
        <inertial>
        <mass value="${mass}" />
        <inertia ixx="1.0" ixy="0.0" ixz="0.0" iyy="1.0" iyz="0.0" izz="1.0" />
        </inertial>
    </xacro:macro>

    <!-- adding world link for Gazebo simulation -->
    <link name="world"/>
    <joint name="world" type="fixed">
        <parent link="world"/>
        <child link="base_link"/>
    </joint>

    <link name="base_link"/>

    <link name="link_0">
        <visual>
            <origin xyz="0 0 ${len1/2}" rpy="0 0 0" />
            <geometry>
                <cylinder radius="${size1}" length="${len1}"/>
            </geometry>
            <material name="black"/>
        </visual>
        <collision>
            <geometry>
                <cylinder radius="${size1}" length="${len1}"/>
            </geometry>
        </collision>
        <xacro:default_inertial mass="10"/>
    </link>

    <joint name="fixed" type="fixed">
        <parent link="base_link"/>
        <child link="link_0"/>
    </joint>

    <xacro:macro name="add_link" params="suffix size_z size">
        
        <xacro:if value="${size==1}">
            <xacro:property name="radius" value="${size1}" />
        </xacro:if>
        <xacro:unless value="${size==1}">
            <xacro:if value="${size==2}">
                <xacro:property name="radius" value="${size2}" />
            </xacro:if>
            <xacro:unless value="${size==2}">
                <xacro:property name="radius" value="${size3}" />
            </xacro:unless>  
        </xacro:unless>

        <link name="link_${suffix}">
            <visual>
                <origin xyz="0 0 ${size_z/2}" rpy="0 0 0" />
                <geometry>
                    <!-- <box size="${radius} ${radius} ${size_z}"/> -->
                    <cylinder radius="${radius}" length="${size_z}"/>
                </geometry>
                <material name="black"/>
                <!-- <xacro:if value="${suffix%2==0}">
                    <material name="white"/>
                </xacro:if>
                <xacro:unless value="${suffix%2==0}">
                    <material name="blue"/>
                </xacro:unless> -->
            </visual>
            <collision>
                <origin xyz="0 0 ${size_z/2}" rpy="0 0 0" />
                <geometry>
                    <!-- <box size="${radius} ${radius} ${size_z}"/> -->
                    <cylinder radius="${radius}" length="${size_z}"/>
                </geometry>
            </collision>
            <inertial>
                <origin xyz="0 0 ${size_z/2}" rpy="0 0 0"/>
                <mass value="${mass}"/>
                <inertia
                ixx="${mass / 12.0 * (radius*radius + size_z*size_z)}" ixy="0.0" ixz="0.0"
                iyy="${mass / 12.0 * (size_z*size_z + radius*radius)}" iyz="0.0"
                izz="${mass / 12.0 * (radius*radius + radius*radius)}"/>
            </inertial>
        </link>
        <gazebo reference="link_${suffix}">
            <mu1>0.2</mu1>
            <mu2>0.2</mu2>
            <kp>1000000.0</kp>
            <kd>1.0</kd>
            <maxVel>0.0</maxVel>
            <minDepth>0.0001</minDepth>
            <material>Gazebo/White</material>
        </gazebo>

    </xacro:macro>

    <xacro:macro name="add_size_adapter" params="suffix size_z size">
        
        <xacro:if value="${size==3}">
            <xacro:property name="radius1" value="${size3}" />
            <xacro:property name="radius2" value="${size2}" />
        </xacro:if>
        <xacro:unless value="${size==3}">
            <xacro:if value="${size==2}">
                <xacro:property name="radius1" value="${size2}" />
                <xacro:property name="radius2" value="${size1}" />
            </xacro:if>
            <xacro:unless value="${size==2}">
                <!-- ERROR! -->
            </xacro:unless>  
        </xacro:unless>

        <link name="link_${suffix}">
            <visual>
                <origin xyz="0 0 ${size_z/4}" rpy="0 0 0" />
                <geometry>
                    <!-- <box size="${radius} ${radius} ${size_z}"/> -->
                    <cylinder radius="${radius1}" length="${size_z/2}"/>
                </geometry>
                <material name="grey"/>
            </visual>
            <visual>
                <origin xyz="0 0 ${3*size_z/4}" rpy="0 0 0" />
                <geometry>
                    <!-- <box size="${radius} ${radius} ${size_z}"/> -->
                    <cylinder radius="${radius2}" length="${size_z/2}"/>
                </geometry>
                <material name="grey"/>
            </visual>
            <collision>
                <origin xyz="0 0 ${size_z/4}" rpy="0 0 0" />
                <geometry>
                    <!-- <box size="${radius} ${radius} ${size_z}"/> -->
                    <cylinder radius="${radius1}" length="${size_z/2}"/>
                </geometry>
            </collision>
            <collision>
                <origin xyz="0 0 ${3*size_z/4}" rpy="0 0 0" />
                <geometry>
                    <!-- <box size="${radius} ${radius} ${size_z}"/> -->
                    <cylinder radius="${radius2}" length="${size_z/2}"/>
                </geometry>
            </collision>
            <inertial>
                <origin xyz="0 0 ${size_z/2}" rpy="0 0 0"/>
                <mass value="${mass}"/>
                <inertia
                ixx="${mass / 12.0 * (radius1*radius1 + size_z*size_z)}" ixy="0.0" ixz="0.0"
                iyy="${mass / 12.0 * (size_z*size_z + radius1*radius1)}" iyz="0.0"
                izz="${mass / 12.0 * (radius1*radius1 + radius1*radius1)}"/>
            </inertial>
        </link>
        <gazebo reference="link_${suffix}">
            <mu1>0.2</mu1>
            <mu2>0.2</mu2>
            <kp>1000000.0</kp>
            <kd>1.0</kd>
            <maxVel>0.0</maxVel>
            <minDepth>0.0001</minDepth>
            <material>Gazebo/Grey</material>
        </gazebo>

    </xacro:macro>

    <xacro:macro name="add_elbow" params="suffix size_y size_z size">

        <xacro:if value="${size==1}">
            <xacro:property name="radius" value="${size1}" />
        </xacro:if>
        <xacro:unless value="${size==1}">
            <xacro:if value="${size==2}">
                <xacro:property name="radius" value="${size2}" />
            </xacro:if>
            <xacro:unless value="${size==2}">
                <xacro:property name="radius" value="${size3}" />
            </xacro:unless>  
        </xacro:unless>

        <link name="link_${suffix}">
            <visual>
                <origin xyz="0 0 ${size_z/2}" rpy="0 0 0" />
                <geometry>
                    <!-- <box size="${radius} ${radius} ${size_z}"/> -->
                    <cylinder radius="${radius}" length="${size_z}"/>
                </geometry>
                <material name="white"/>
                <!-- <xacro:if value="${suffix%2==0}">
                    <material name="white"/>
                </xacro:if>
                <xacro:unless value="${suffix%2==0}">
                    <material name="blue"/>
                </xacro:unless> -->
            </visual>
            <visual>
                <origin xyz="0 ${size_y/2} ${size_z}" rpy="1.57 0 0" />
                <geometry>
                    <!-- <box size="${radius} ${size_y} ${radius}"/> -->
                    <cylinder radius="${radius}" length="${size_y}"/>
                </geometry>
                <material name="white"/>
                <!-- <xacro:if value="${suffix%2==0}">
                    <material name="white"/>
                </xacro:if>
                <xacro:unless value="${suffix%2==0}">
                    <material name="blue"/>
                </xacro:unless> -->
            </visual>
            <visual>
                <origin xyz="0 0 ${size_z}" rpy="0 0 0" />
                <geometry>
                    <sphere radius="${radius}" />
                </geometry>
                <material name="white"/>
            </visual>
            <collision>
                <origin xyz="0 0 ${size_z/2}" rpy="0 0 0" />
                <geometry>
                    <!-- <box size="${radius} ${radius} ${size_z}"/> -->
                    <cylinder radius="${radius}" length="${size_z}"/>
                </geometry>
            </collision>
            <inertial>
                <origin xyz="0 0 ${size_z/2}" rpy="0 0 0"/>
                <mass value="${mass}"/>
                <inertia
                ixx="${mass / 12.0 * (radius*radius + size_z*size_z)}" ixy="0.0" ixz="0.0"
                iyy="${mass / 12.0 * (size_z*size_z + radius*radius)}" iyz="0.0"
                izz="${mass / 12.0 * (radius*radius + radius*radius)}"/>
            </inertial>
            <collision>
                <origin xyz="0 ${size_y/2} ${size_z}" rpy="1.57 0 0" />
                <geometry>
                    <!-- <box size="${radius} ${size_y} ${radius}"/> -->
                    <cylinder radius="${radius}" length="${size_y}"/>
                </geometry>
            </collision>
            <collision>
                <origin xyz="0 0 ${size_z}" rpy="0 0 0" />
                <geometry>
                    <sphere radius="${radius}" />
                </geometry>
            </collision>
        </link>
        <gazebo reference="link_${suffix}">
            <mu1>0.2</mu1>
            <mu2>0.2</mu2>
            <kp>1000000.0</kp>
            <kd>1.0</kd>
            <maxVel>0.0</maxVel>
            <minDepth>0.0001</minDepth>
            <material>Gazebo/White</material>
        </gazebo>

    </xacro:macro>

    <xacro:macro name="add_fixed_joint" params="suffix x y z roll pitch yaw">    
        <joint name="fixed_joint_${suffix}" type="fixed">
            <axis xyz="0 0 1" rpy="0 0 0" />
        
            <parent link="link_${suffix}"/>

            <!-- <parent link="base_link"/> -->
            <child link="link_${suffix}_bis"/>
            <origin xyz="${x} ${y} ${z}" rpy="${roll} ${pitch} ${yaw}"/>
        </joint>
    </xacro:macro>

    <xacro:macro name="add_joint" params="suffix x y z roll pitch yaw upper_lim lower_lim effort velocity">    
        <joint name="joint_${suffix}" type="revolute">
            <axis xyz="0 0 1" rpy="0 0 0" />
        
            <parent link="link_stator_joint_${suffix}"/>

            <!-- <parent link="base_link"/> -->
            <child link="link_${suffix}"/>
            <origin xyz="${x} ${y} ${z}" rpy="${roll} ${pitch} ${yaw}"/>
            <limit lower="${lower_lim}" upper="${upper_lim}" effort="${effort}" velocity="${velocity}"/>
        </joint>
        <link name="link_${suffix}"/>

    </xacro:macro>

    <xacro:macro name="add_joint_stator" params="suffix size_y size_z size">

        <xacro:if value="${size==1}">
            <xacro:property name="radius" value="${size1}" />
        </xacro:if>
        <xacro:unless value="${size==1}">
            <xacro:if value="${size==2}">
                <xacro:property name="radius" value="${size2}" />
            </xacro:if>
            <xacro:unless value="${size==2}">
                <xacro:property name="radius" value="${size3}" />
            </xacro:unless>  
        </xacro:unless>
        
        <link name="link_stator_joint_${suffix}">
            <visual>
                <origin xyz="0 0 ${size_z/2}" rpy="0 0 0" />
                <geometry>
                    <cylinder radius="${radius}" length="${size_z}"/>
                </geometry>
                <material name="blue"/>
            </visual>
            <collision>
                <origin xyz="0 0 ${size_z/2}" rpy="0 0 0" />
                <geometry>
                    <cylinder radius="${radius}" length="${size_z}"/>
                </geometry>
            </collision>
            <inertial>
                <origin xyz="0 0 ${size_z/2}" rpy="0 0 0"/>
                <mass value="${mass}"/>
                <inertia
                ixx="${mass / 12.0 * (radius*radius + size_z*size_z)}" ixy="0.0" ixz="0.0"
                iyy="${mass / 12.0 * (size_z*size_z + radius*radius)}" iyz="0.0"
                izz="${mass / 12.0 * (radius*radius + radius*radius)}"/>
            </inertial>
        </link>
        <gazebo reference="link_stator_joint_${suffix}">
            <mu1>0.2</mu1>
            <mu2>0.2</mu2>
            <kp>1000000.0</kp>
            <kd>1.0</kd>
            <maxVel>0.0</maxVel>
            <minDepth>0.0001</minDepth>
            <material>Gazebo/Blue</material>
        </gazebo>

    </xacro:macro>

    <xacro:macro name="add_fixed_joint_stator" params="suffix suffix_bis x y z roll pitch yaw">    
        <joint name="fixed_joint_${suffix_bis}" type="fixed">
            <axis xyz="0 0 1" rpy="0 0 0" />
        
            <parent link="link_${suffix_bis}"/>

            <!-- <parent link="base_link"/> -->
            <child link="link_stator_joint_${suffix}"/>
            <origin xyz="${x} ${y} ${z}" rpy="${roll} ${pitch} ${yaw}"/>
        </joint>
    </xacro:macro>

    <!-- <xacro:macro name="add_link_elbow" params="suffix p n x y z roll pitch yaw">
        
        <link name="link_${suffix}">
            <visual>
                <origin xyz="0 0 ${p/2}" rpy="0 0 0" />
                <geometry>
                <box size="${size1} ${size1} ${p}"/>
                </geometry>
                <xacro:if value="${suffix%2==0}">
                    <material name="white"/>
                </xacro:if>
                <xacro:unless value="${suffix%2==0}">
                    <material name="blue"/>
                </xacro:unless>
            </visual>
            <visual>
                <origin xyz="0 ${n/2} ${p}" rpy="0 0 0" />
                <geometry>
                <box size="${size1} ${n} ${size1}"/>
                </geometry>
                <xacro:if value="${suffix%2==0}">
                    <material name="white"/>
                </xacro:if>
                <xacro:unless value="${suffix%2==0}">
                    <material name="blue"/>
                </xacro:unless>
            </visual>
            <visual>
                <origin xyz="0 0 -0.05" rpy="0 0 0" />
                <geometry>
                <box size="${size1} ${size1} 0.1"/>
                </geometry>
                <material name="black"/>
            </visual>
            <collision>
                <origin xyz="0 0 ${p/2}" rpy="0 0 0" />
                <geometry>
                <box size="${size1} ${size1} ${p}"/>
                </geometry>
            </collision>
            <collision>
                <origin xyz="0 ${n/2} ${p}" rpy="0 0 0" />
                <geometry>
                <box size="${size1} ${n} ${size1}"/>
                </geometry>
            </collision>
            <collision>
                <origin xyz="0 0 -0.05" rpy="0 0 0" />
                <geometry>
                <box size="${size1} ${size1} 0.1"/>
                </geometry>
                <material name="black"/>
            </collision>
            <xacro:default_inertial mass="1"/>
        </link>

        <joint name="joint_${suffix-1}_${suffix}" type="continuous">
            <axis xyz="0 0 1" rpy="0 0 0" />
        
            <parent link="link_${suffix-1}"/>

            <child link="link_${suffix}"/>
            <origin xyz="${x} ${y} ${z}" rpy="${roll} ${pitch} ${yaw}"/>
        </joint>
    </xacro:macro> -->

</robot>