# solver_options:
#     regularization: 1e-6
#     back_end: qpoases
#     control_dt: 0.001
# stack:
#     -   - EE_1
#         - EE_2
stack:
    - [EE]
# constraints:
#     ["JointLimits", "VelocityLimits"]
# EE_1:
#     type: Interaction
#     base_link: L_0_A
#     distal_link: ee_A
# EE_2:
#     type: Interaction
#     base_link: L_0_B
#     distal_link: ee_B
EE:
    type: Interaction
    base_link: ee_B
    distal_link: ee_A
    indices: [0,1,2,3,4]
    stiffness:
        - 50.0
        - 50.0
        - 50.0
        - 1.0
        - 1.0
        - 1.0
    damping:
        - 5.0
        - 5.0
        - 5.0
        - 0.0
        - 0.0
        - 0.0

