solver_options:
    regularization: 1e-6
    back_end: "qpoases"
    control_dt: 0.001

stack:
    - ["EE_1", "EE_2"]

constraints: ["JointLimits"]

EE_1:
    type: Cartesian
    base_link: bl1
    distal_link: ee1

EE_2:
    type: Cartesian
    base_link: bl2
    distal_link: ee2
