
stack:
- [EE]


EE:
    type: Interaction
    base_link: base_link
    distal_link: tool_exchanger_A
    stiffness: [50.0, 50.0, 50.0, 1.0, 1.0, 1.0] 
    damping: [5.0, 5.0, 5.0, 0.0, 0.0, 0.0]
    

