on:
  # Compare the preceeding commit -> to the current commit of the main branch.
  # (Note: To compare changes between the current commit to the last pushed remote commit of the main branch set `since_last_remote_commit: true`)
  # push:
    # branches:
      # - main
      
  # Compare the last commit of main -> to the current commit of a PR branch.
  # (Note: To compare changes between the current commit to the last pushed remote commit of a PR branch set `since_last_remote_commit: true`)
  pull_request:
    branches:
      - alberobotics
  
jobs:
  build:
    runs-on: ubuntu-latest  # windows-latest | macos-latest
    name: check changed-files
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0  # OR "2" -> To retrieve the preceding commit.

      # Example 1
      - name: Get changed files
        id: changed-files
        uses: tj-actions/changed-files@v35

      - name: List all changed files
        run: |
          to_check=(
          "src/modular/modular_data/configs/ModularBot_xbot2.yaml"
          "src/modular/modular_data/configs/low_level/hal/ModularBot_dummy.yaml"
          "src/modular/modular_data/configs/low_level/hal/ModularBot_ec_all.yaml"
          "src/modular/modular_data/configs/low_level/hal/ModularBot_gz.yaml"
          "src/modular/modular_data/configs/low_level/joint_config/ModularBot_idle.yaml"
          "src/modular/modular_data/configs/low_level/joint_config/ModularBot_impd4.yaml"
          "src/modular/modular_data/cartesio/ModularBot_cartesio_config.yaml"
          "src/modular/modular_data/cartesio/ModularBot_cartesio_IK_config.yaml"
          "src/modular/modular_data/cartesio/ModularBot_cartesio_Interaction_config.yaml"
          "src/modular/modular_data/cartesio/ModularBot_cartesio_multichain_config.yaml")

          for file in ${{ steps.changed-files.outputs.all_changed_files }}; do
            for i in ${!to_check[@]}; do
              if [ $file == $i ]
                echo "$file was changed"
                exit 1
              fi
            done
          done