name: Create pull request 

on:
  push:
    branches:
      - 'master'

jobs:
  create_pull_request:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    # Make changes to pull request here
    - name: Create Pull Request
      uses: peter-evans/create-pull-request@v4
      with:
        committer: "marcoruzzon"
        labels: |
            automated pr
